#version 450
layout(local_size_x = 4) in;
layout(set = 0, binding = 0) readonly buffer InputData {
    vec4 inputData[];
};
layout(set = 0, binding = 1) writeonly buffer OutputData {
    vec4 outputData[];
};

void main() {
    uint index = gl_GlobalInvocationID.x;
    vec4 value = vec4(0.0);
    float iteration = 0.0;
    while (iteration < 10.0) {
        if (iteration >= 3.0) {
            break;
        }
        value += inputData[index];
        iteration += 1.0;
    }
    outputData[index] = value;
}
